### ISSUE TITLE
Suggerimenti Ui e UX

### ISSUE THREAD

**Issue by lvercellati** [marcosqlbi/vaccination-italy#1]
Ciao,
di seguito alcuni suggerimenti per migliorare User Interface e User Experience:

1. Separare i visual con un background di pagina per migliorare la leggibilità
2. Cambiare label bottone Torna Indietro in Torna Home perché rimanda sempre alla prima pagina, ma non è detto che l'utente sia arrivato da quella pagina
3. Modificare la visual interaction da highlight a filter per permettere di visualizzare una sola categoria nei grafici stacked dove altrimenti le categorie successive alla prima sono di difficile valutazione nel loro dettaglio
4. Pagina 2 l'interazione dei vari visual con il grafico in basso a destra (è un unico grafico in small multiples?) agisce in maniera diversa sui diversi grafici (Pfizer in highlight e gli altri in filter)
5. Valutare se può avere senso aggiungere uno slicer Fornitore nelle pagine in cui è presente nei grafici per migliorare la valutazione delle singole categorie (vedi punto 3)

Se doveste avere bisogno di un aiuto per qualcosa, chiedete pure.
Lorenzo

**Comment by marcosqlbi** [comment]
Ciao Lorenzo,

grazie per i consigli - vuoi scaricare il PBIX e collaborare? L'unico problema è che non esiste un sistema per gestire bene la concorrenza, quindi bisogna lavorare mentre non sta lavorando qualcun altro e poi pubblicare su GitHub - oppure scarichi il PBIX, lo modifichi e me lo mandi via mail - per me è più semplice fare copia/incolla dei visual nel caso e ottenere una versione aggiornata. In ogni caso su Power BI devo poi pubblicarlo io per mantenere l'URL pubblico.
Fammi sapere, grazie!

**Comment by lvercellati** [comment]
Ciao Marco,
collaboro volentieri.
Scarico il pbix, vedo di applicare i suggerimenti di cui sopra e poi ti mando il pbix via mail, così gestisci tu al meglio come e quando portare le modifiche che faccio io.

**Comment by marcosqlbi** [comment]
Perfetto, grazie!
