### ISSUE TITLE
Pagina Somministrazioni / Slicers

### ISSUE THREAD

**Issue by lvercellati** [marcosqlbi/vaccination-italy#2]
Ciao,
nella pagina delle somministrazioni, agendo sugli slicer della Categoria e/o del genere il visual delle dosi 1 e 2 non riporta dati.
Il filtro su Periodo selezionato/ Totale cumulato penso debba avere la selezione unica, se ne ho ben inteso il funzionamento.

Lorenzo

**Comment by marcosqlbi** [comment]
Questo avviene perché i dati non consentono di andare a quel livello di dettaglio. Cosa intendi per "selezione unica" ?

**Comment by lvercellati** [comment]
Intendo che o scelgo di vedere i dati per Periodo selezionato oppure per totale cumulato e quindi mi aspetterei che una selezione escluda l'altra: in parole povere mi aspetterei il radio button e non il check, perché con il secondo posso selezionare tutte e due le opzioni ma il grafico ne applica sempre una. O sbaglio?

**Comment by marcosqlbi** [comment]
Sì hai ragione - mi sembra che sia così nella nuova versione che hai mandato. Grazie!
